# when using the default proxy server port
# local_backend: true

backend:
    name: git-gateway
    branch: main
    repo: laurelschwulst/alt-text-selfies

media_folder: "/assets/sounds"
public_folder: "/assets"

collections:
  - name: "selfies"
    label: "Selfies"
    folder: "selfies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Selfie Text", name: "body", widget: "markdown" }
      - { label: "Is in chapbook?", name: "is-in-chapbook", widget: "boolean", default: false }
      - { label: "Audio", name: "audio", widget: "file"}
  - name: "essays"
    label: "Essays"
    folder: "essays"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Essay Text", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "about"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content', label: 'Content', widget: 'markdown' }
