# when using the default proxy server port
# local_backend: true

backend:
    name: git-gateway
    branch: main
    repo: laurelschwulst/alt-text-selfies

media_folder: "/assets/sounds"
public_folder: "/assets"

collections:
  - name: "selfies"
    label: "Selfies"
    folder: "selfies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Selfie Text", name: "body", widget: "markdown" }
      - { label: "Is in chapbook?", name: "is-in-chapbook", widget: "boolean", default: false }
      - { label: "Audio", name: "audio", widget: "file", required: false, media_folder: "/assets/sounds" }
  - name: "essays"
    label: "Essays"
    folder: "essays"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Essay Text", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Welcome"
        name: "welcome"
        file: "welcome.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Welcome Text", name: "body", widget: "markdown" }
      - label: "Book"
        name: "book"
        file: "book.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Book Text", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About Text", name: "body", widget: "markdown" }
      - label: "Links"
        name: "links"
        file: "links.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Links Text", name: "body", widget: "markdown" }