backend:
    name: git-gateway
    branch: master

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "selfies"
    label: "selfies"
    folder: "selfies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/selfie.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Selfie Text", name: "body", widget: "markdown" }
