# when using the default proxy server port
local_backend: true

backend:
    name: git-gateway
    branch: main
    repo: laurelschwulst/alt-text-selfies

media_folder: "/assets/sounds"
public_folder: "/assets"

collections:
  - name: "selfies"
    label: "selfies"
    folder: "selfies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Selfie Text", name: "body", widget: "markdown" }
      - { label: "Is in chapbook?", name: "is-in-chapbook", widget: "boolean", default: false }
      - { label: "Audio", name: "audio", widget: "file"}
